package util;

import client.ClientStatistics;

/**
 * Utility class to print formatted monitoring reports to the console for both
 * the UDP Server and UDP Clients.
 */
public class ConsoleReport {

    /**
     * Prints formatted statistics report for the UDP Server.
     *
     * @param packetsGenerated Total unique packets generated by server
     * @param clientsConnected Count of registered target clients
     * @param totalPacketsSent Total packets sent across all clients (generated * clients)
     * @param totalBytesSent    Total bytes transmitted over UDP datagrams
     * @param sendingTimeMs     Total transmission execution time in milliseconds
     */
    public static void printServerReport(long packetsGenerated, int clientsConnected,
                                        long totalPacketsSent, long totalBytesSent,
                                        long sendingTimeMs) {
        double avgPacketSize = totalPacketsSent > 0 ? (double) totalBytesSent / totalPacketsSent : 0.0;
        double throughputMBps = sendingTimeMs > 0 ? ((double) totalBytesSent / (1024.0 * 1024.0)) / ((double) sendingTimeMs / 1000.0) : 0.0;

        System.out.println();
        System.out.println("==================== SERVER ====================");
        System.out.printf("Packets Generated   : %d%n", packetsGenerated);
        System.out.printf("Clients Connected   : %d%n", clientsConnected);
        System.out.printf("Packets Sent        : %d%n", totalPacketsSent);
        System.out.printf("Bytes Sent          : %d bytes%n", totalBytesSent);
        System.out.printf("Average Packet Size : %.2f bytes%n", avgPacketSize);
        System.out.printf("Sending Time        : %d ms%n", sendingTimeMs);
        System.out.printf("Throughput          : %.2f MB/s%n", throughputMBps);
        System.out.println("===============================================");
        System.out.println();
    }

    /**
     * Prints formatted statistics report for a UDP Client.
     *
     * @param clientId Identifier or label of the client
     * @param stats    ClientStatistics object containing captured metrics
     */
    public static void printClientReport(String clientId, ClientStatistics stats) {
        System.out.println();
        System.out.printf("==================== CLIENT (%s) ====================%n", clientId);
        System.out.printf("Packets Expected  : %d%n", stats.getExpectedPackets());
        System.out.printf("Packets Received  : %d%n", stats.getReceivedPackets());
        System.out.printf("Packets Lost      : %d%n", stats.getLostPackets());
        System.out.printf("Duplicate Packets : %d%n", stats.getDuplicatePackets());
        System.out.printf("Out Of Order      : %d%n", stats.getOutOfOrderPackets());
        System.out.printf("Average Delay     : %.2f ms%n", stats.getAverageDelayMs());
        System.out.printf("Minimum Delay     : %d ms%n", stats.getMinDelayMs());
        System.out.printf("Maximum Delay     : %d ms%n", stats.getMaxDelayMs());
        System.out.printf("Bytes Received    : %d bytes%n", stats.getBytesReceived());
        System.out.printf("Receive Rate      : %.2f pps%n", stats.getPacketsPerSecond());
        System.out.println("====================================================");
        System.out.println();
    }
}
